#!/usr/bin/env bash

clear

array=( '/var/www/vhosts' '/home/' '/home/user/programming/rust' '/home/user/programming/python' '/mnt/raid/backup_of_hippy_server' )
for folder in "${array[@]}"
do
	echo ${folder}
	show_status -d ${folder}done
done
